mkdocs_click/_extension.py
Prompted by CI failures across the board that show:
```
+ venv/bin/mypy mkdocs_click tests
mkdocs_click/_extension.py:48: error: "Markdown" has no attribute "parser"
mkdocs_click/_extension.py:49: error: "Markdown" has no attribute "preprocessors"
Found 2 errors in 1 file (checked 15 source files)
```
=> Fix type error on latest mypy

requirements.txt
**Motivation**
By strictly pinning dev deps, we can prevent issues like #16 from happening again without notice.
=> Pin dev dependencies

setup.py
**Motivation**
Prevent breakage due to `click` or `markdown` bumping major versions. If that happens, users may start noticing and letting us know, and we could then look at adding support for 8.* or 4.*.
=> Properly pin `click` and `markdown` dependencies to current major versions

CONTRIBUTING.md, example/index.md, mkdocs.yml, scripts/docs
**Description**
Add a local `example` docs site that renders the CLI of `mkdocs` itself through `mkdocs-click`.
**Motivation**
This will make it easier to iterate quickly on `mkdocs-click`.
=> Add example docs site

tests/test_extension.py
Follow-up for #8.
This PR adds a unit test for the new `:prog_name:` option.
=> Add test for prog_name option

scripts/install
Alternative to #13
Some contributors may have `python` referring to Python 2. Most people should have `python3` referring to a proper Python 3.x executable (even pyenv users), so let's use that instead.
=> Use "python3 as the executable when installing deps

CHANGELOG.md, mkdocs_click/__version__.py
Changelog source: https://github.com/DataDog/mkdocs-click/compare/0.1.1...7a6fd098
`integrations-core` notes: we are properly pinning to `0.1.*`, so this shouldn't affect us in any way. We can look at upgrading once this release is out.
https://github.com/DataDog/integrations-core/blob/1d69a6ef48858b50bad753eea57c4ca5ab85a2e1/tox.ini#L34-L35
- Add `:prog_name:` option to allow overriding the name of the CLI program. (Pull #8, contributed by @frankier.)
- Add official support for Python 3.9. (Pull #20)
- Properly pin `click==7.*` and `markdown==3.*`. (Pull #19)
=> Version 0.2.0

mkdocs_click/_docs.py, tests/app/expected.md, tests/unit/test_docs.py
Closes #26 
Ensure `--help` is kept as part of the raw "Options" block. This means the block will be present for all commands.
This means simpler logic, which will help with implementing table output, refs #11.
=> Keep --help as part of options raw output

README.md, mkdocs_click/_docs.py, mkdocs_click/_extension.py, tests/app/expected.md, tests/unit/test_docs.py
Rewrite of #12 in a backward-compatible manner.
One difference from what @florimondmanca and I discussed is that I named the option `:option-style:`. This is more descriptive than `style` and easy to extend when we want to define styles for other sections such as usage.
Fix #11.
=> Add table style for option formatting

README.md, mkdocs_click/_docs.py, mkdocs_click/_extension.py, tests/unit/test_docs.py
Follow-up for #25, refs #11
* Fix : `:option-style:` -> `:style:` for consistency with other option names.
* Fix: pass `style` to sub-commands (otherwise only top command would be formatted using the given `style`)
* Refactor table formatting logic using extra intermediary functions.
* Add a bunch of comments to help with readability and understanding of the code.
* Some other nits.
=> Clean up table formatting

mkdocs_click/_docs.py, mkdocs_click/_extension.py, tests/app/cli.py, tests/test_extension.py, tests/unit/test_docs.py
This PR ensures the `prog_name` (introduced by #8 and initially requested in #6) is also used in the usage sections.
This is achieved by properly setting the `info_name` for the [click.Context](https://click.palletsprojects.com/en/7.x/api/#context) used during documentation rendering.  Setting the `info_name` allows click to properly populate the `ctx.command_path` property and thus `_docs.py line 77` now actually combines the command path and the pieces correctly. In the previous version `ctx.command_path` was always empty. This makes the custom command path building logic obsolete.
Now as a side effect this produces one failing test:
```python
def test_custom_multicommand_name():
"""Custom multi commands must be given a name."""
multi = MultiCLI()
with …
```
=> Use prog_name for usage

mkdocs_click/_docs.py, tests/app/expected.md, tests/unit/test_docs.py
Alternative to #14 
**Description**
Make "Usage" and "Options" headings for each command `**bold**`.
**Motivation**
Tweak legibility and navigation.
Before / After:
=> Make usage and options headings bold

mkdocs_click/_docs.py, mkdocs_click/_extension.py, tests/test_docs.py
Small internal refactoring: we expose `:depth:  as an option, but use `level=...` internally. Let's use `depth` everywhere.
=> Rename level=... to depth=... for consistency

README.md, mkdocs.yml, mkdocs_click/_docs.py, mkdocs_click/_extension.py, setup.py, tests/app/expected-enhanced.md, tests/test_extension.py
Closes #35 
Allows progressively enhancing rendering to output full command paths, instead of only command names.
The only change is that headers show eg `ddev env ls` instead of `ls`, and permalinks are eg `#ddev-env-ls` instead of `#ls`.
We need the `attr_list` extension to be installed, so to bring this change progressively we check for the extension instead of making it a hard-requirement, and keep the old behavior as a fallback (AKA progressive enhancement). This does take a bit of additional code.
For cases when `attr_list` is already present, I think this behavior is better in any case, so no need for a "force-disable" flag.
=> Allow using full command paths in headers

CHANGELOG.md, mkdocs_click/__version__.py
Changelog source: https://github.com/DataDog/mkdocs-click/compare/0.2.0...7b50e5d
- `--help` is now kept in options (it used to be automatically dropped). (Pull #29)
- Add table formatting. (Pulls #25, #30)
- Use `:prog_name:` more consistently in usage. (Pull #24)
- Make usage and options headings bold to improve legibility. (Pull #31)
=> Version 0.3.0

mkdocs_click/_docs.py
Options with None as default value are not handled correctly.
This PR fixes the issue.
e.g.
```python
@click.option("-m", "--message", required=False, default=None)
```
=> Correctly handle default values of `None`

README.md, mkdocs_click/_docs.py, mkdocs_click/_extension.py, tests/app/cli.py, tests/test_docs.py
Resolves #51 
The changes are rather simple, except the `_make_plain_options()` where I had to hack it a bit to make Click's formatter notice hidden options.
=> Add `show_hidden` option

.github/workflows/publish.yml
Motivation: https://datadoghq.atlassian.net/browse/SINT-948
I do not have the permission to add new secrets to this project so I can't add the token myself.
=> Use an API token to publish to PyPi

mkdocs_click/_docs.py, tests/app/expected-enhanced.md, tests/app/expected-sub-enhanced.md, tests/app/expected-sub.md, tests/app/expected.md, tests/test_docs.py
This ensures the code block isn't highlighted even with highlight.js
Before/after comparison on "mkdocs" theme:
=> Add the code blocks as ```text to avoid highlighting

CHANGELOG.md, mkdocs_click/_processing.py, tests/test_processing.py
This PR is based on and supersedes the one in #44. I added more explanation, a test, and fixed a small bug with trailing whitespace.
--- 
When documenting subcommands, sometimes mkdocs-click will only show the
subcommand name. `:prog_name:` seems to be the right option to ensure
the actuall command is shown, but due to an overly-strict regex, it
used to ignore everything after the first whitespace. With this change,
`prog_name` and other commands can contain multiple words in their
values.
For example
```
::: mkdocs-click
:module: foo.utils.bridge
:prog_name: foo-utils bridge
:command: cli
```
now properly renders as
> foo-utils bridge [OPTIONS]
instead of
> foo-utils [OPTIONS]
or
> bridge [OPTIONS]
(^^ if prog_name wasn't specified at all)
Co-Authored-By: Bar Hochman …
=> Allow options to contain multiple words

CHANGELOG.md, mkdocs_click/_docs.py, mkdocs_click/_extension.py, mkdocs_click/_loader.py, tests/app/cli.py, tests/test_docs.py, tests/test_extension.py
See https://github.com/mkdocs/mkdocs-click/pull/81#issuecomment-2781543337
=> Broaden support for core classes

CHANGELOG.md, mkdocs_click/_docs.py
When creating a context from the command, the context settings were not propagated, which means that some options set on the command would be ignored.
To illustrate:
```py
import click
@click.command(context_settings={"help_option_names": ["-h", "--help"], "show_default": True})
@click.option("-t", "--test", type=int, default=42)
def cli(test):
print("the number is", test)
```
Now compare `ctx.get_help()` when the context is and is not passed through:
```py
>>> ctx = click.Context(cli)
>>> print(ctx.get_help())
Usage:  [OPTIONS]
Options:
-t, --test INTEGER
--help              Show this message and exit.
>>> ctx = click.Context(cli, **cli.context_settings)
>>> print(ctx.get_help())
Usage:  [OPTIONS]
Options:
-t, --test INTEGER  [default: 42]
-h, --help          Show this message and exit. …
```
=> pass command.context_settings to new context

README.md
I could not have it working since I had them in wrong order
I could not find a way to have both orders working by changing the code
=> Full command path headers: add note regarding md extensions order
